#pragma once
#define LEFT_COLUMN 5
#define RIGHT_COLUMN 500+5
#define HEADER_ROW 5
#define ROW_HEIGHT 25
#define COLUMN_WIDTH 100
#define ROW1 50+5
#define ROW2 ROW1 + ROW_HEIGHT
#define ROW3 ROW2 + ROW_HEIGHT
#define ROW4 ROW3 + ROW_HEIGHT
#define ROW5 ROW4 + ROW_HEIGHT
#define ROW6 ROW5 + ROW_HEIGHT
#define ROW7 ROW6 + ROW_HEIGHT
#define ROW8 ROW7 + ROW_HEIGHT
#define ROW9 ROW8 + ROW_HEIGHT
#define ROW10 ROW9 + ROW_HEIGHT
#define NUM_COLUMNS 4
#define NUM_ROWS 10